apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: task-git
spec:
  workspaces:
  - name: data
  params:
    - name: TASK_INSTANCE_ID
      description: "taskInstanceId is used to update results"
    - name: FLOW_INSTANCE_ID
      description: "flowInstanceId is used to update results"
    - name: REPO_URL
      description: "Repository URL to clone from."
    - name: REPO_REVISION
      description: "Revision to checkout. (branch, tag, sha, ref, etc...)"
    - name: CLONE_DEPTH
      description: "depth of a shallow clone"
      default: "1"
    - name: WORKING_PATH
      description: "default working path"
      default: "."
  tasks:
    - name: main
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.REPO_URL)
        - name: revision
          value: $(params.REPO_REVISION)
        - name: depth
          value: $(params.CLONE_DEPTH)
        - name: working-path
          value: $(params.WORKING_PATH)
      workspaces:
        - name: data
          workspace: data
  finally:
    - name: post
      taskRef:
        name: post-handler
      params:
        - name: main-task-status
          value: "$(tasks.main.status)"
        - name: taskInstanceId
          value: $(params.TASK_INSTANCE_ID)
        - name: flowInstanceId
          value: $(params.FLOW_INSTANCE_ID)
        - name: working-path
          value: $(params.WORKING_PATH)
        - name: task-script
          value: "task_git_post_handler.py"
      workspaces:
        - name: data
          workspace: data