apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: task-node
spec:
  workspaces:
  - name: data
  - name: cache
    optional: true
  params:
    - name: TASK_INSTANCE_ID
      description: "taskInstanceId is used to update results"
    - name: FLOW_INSTANCE_ID
      description: "flowInstanceId is used to update results"
    - name: WORKING_PATH
      description: "default working path"
      default: "."
    - name: TASK_SCRIPT
      description: "bash script encoded with base64"
      default: "bnBtIGluc3RhbGw7IG5wbSBydW4gYnVpbGQ="
    - name: TASK_IMAGE
      description: "container image used by maven task"
      default: "node:alpine3.18"
  tasks:
    - name: main
      taskRef:
        name: node
      params:
        - name: working-path
          value: $(params.WORKING_PATH)
        - name: task-script
          value: $(params.TASK_SCRIPT)
        - name: taskImage
          value: $(params.TASK_IMAGE)
      workspaces:
        - name: data
          workspace: data
        - name: cache
          workspace: cache
  finally:
    - name: post
      taskRef:
        name: post-handler
      params:
        - name: main-task-status
          value: "$(tasks.main.status)"
        - name: taskInstanceId
          value: $(params.TASK_INSTANCE_ID)
        - name: flowInstanceId
          value: $(params.FLOW_INSTANCE_ID)
        - name: working-path
          value: $(params.WORKING_PATH)
        - name: task-script
          value: "common_post_handler.py"