apiVersion: v1
kind: Secret
metadata:
  name: git-basic-auth-4-post-task
  annotations:
    tekton.dev/git-0: https://github.com # Described below
type: kubernetes.io/basic-auth
stringData:
  username: xsoloking
  password: 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
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: git-basic-auth-4-post-task
#  annotations:
#    tekton.dev/git-0: https://gitlab.devops.poc # Described below
#type: kubernetes.io/basic-auth
#stringData:
#  username: root
#  password: hSbmxkzDzPn4bqBQwbPg




