apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: node
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.38.0"
    devops.flow/categories: "other"
    tekton.dev/platforms: "linux/amd64,linux/arm64"
spec:
  description: >-
    These Tasks are used to execute bash script in the Pipeline.
  workspaces:
    - name: data
      description: The data of pipeline/task in this Workspace.
    - name: cache
      description: npm cache shared in maven task
      optional: true
  params:
    - name: working-path
      description: dafault working path
      default: "."
    - name: taskImage
      description: task image
      default: "node:alpine3.18"
    - name: task-script
      description: bash script encoded with base64
      default: "bnBtIGluc3RhbGw7IG5wbSBydW4gYnVpbGQ="
  steps:
    - name: executor
      image: "$(params.taskImage)"
      workingDir: "$(workspaces.data.path)/$(params.working-path)"
      env:
      - name: WORKING_PATH
        value: "$(workspaces.data.path)/$(params.working-path)"
      - name: TASK_SCRIPT
        value: "$(params.task-script)"
#      securityContext:
#        runAsNonRoot: true
#        runAsUser: 65532
      volumeMounts:
      - name: build-cache
        mountPath: /root/.npm
      script: |
        #!/usr/bin/env sh
        if [ -d "/workspace/cache" ]; then
          mkdir -p /root/.npm
          ln -s /workspace/cache /root/.npm
        fi
        echo $TASK_SCRIPT | base64 -d | sh
